[package]
name = "sv-elaborator"
version = "0.1.0"
authors = ["Gary Guo <gary@garyguo.net>"]
edition = "2021"

[dependencies]
num = "0.2"
lazycell = "1.2"
colored = "1.6"
lazy_static = "1.2.0"
getopts = "0.2"
